# SPDX-License-Identifier: Apache-2.0

name: 'python_setup'
description: 'Setup for Python and uv'

inputs:
  python-version:
    description: 'Python version, supporting MAJOR.MINOR only'
    required: true
  uv-version:
    description: 'uv version, default latest'
    required: false
    default: 'latest'
  enable-cache:
    description: 'Enable caching uv cache, default true'
    required: false
    default: 'true'
  save-cache:
    description: 'Save the uv cache, false if pull_request'
    required: false
    default: ${{ github.event_name != 'pull_request' }}

runs:
  using: "composite"
  steps:
    - name: 'Setup Python ${{ inputs.python-version }}'
      id: setup-python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: 'Setup uv ${{ inputs.uv-version }}'
      id: setup-uv
      uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      with:
        python-version: ${{ steps.setup-python.outputs.python-version }}
        version: ${{ inputs.uv-version }}
        enable-cache: ${{ inputs.enable-cache }}
        save-cache: ${{ inputs.save-cache }}
